#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr coalesce
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr filter_out
#' @importFrom dplyr first
#' @importFrom dplyr group_by
#' @importFrom dplyr if_else
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr right_join
#' @importFrom dplyr row_number
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr ungroup
#' @importFrom lubridate as_date
#' @importFrom lubridate as.difftime
#' @importFrom lubridate days
#' @importFrom lubridate year
#' @importFrom lubridate years
#' @importFrom lubridate ymd
#' @importFrom rapbase autoReportFormatInput
#' @importFrom rapbase autoReportOrgInput
#' @importFrom rapbase autoReportInput
#' @importFrom rapbase autoReportUI
#' @importFrom rapbase exportGuideUI
#' @importFrom rapbase exportUCInput
#' @importFrom rapbase loadRegData
#' @importFrom rapbase navbarWidgetInput
#' @importFrom rapbase rapTheme
#' @importFrom rapbase regTitle
#' @importFrom rapbase renderRmd
#' @importFrom rapbase statsInput
#' @importFrom rapbase statsGuideUI
#' @importFrom rapbase statsUI
#' @importFrom rapwhale les_dd_mrs
#' @importFrom rapwhale les_kb_mrs
#' @importFrom shiny dateRangeInput
#' @importFrom shiny downloadButton
#' @importFrom shiny htmlOutput
#' @importFrom shiny mainPanel
#' @importFrom shiny navbarMenu
#' @importFrom shiny navbarPage
#' @importFrom shiny radioButtons
#' @importFrom shiny reactive
#' @importFrom shiny renderUI
#' @importFrom shiny sidebarLayout
#' @importFrom shiny sidebarPanel
#' @importFrom shiny tabPanel
#' @importFrom shiny tagList
#' @importFrom shiny uiOutput
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_remove
#' @importFrom stringr str_remove_all
#' @importFrom tibble as_tibble
#' @importFrom tibble tibble
#' @importFrom tidyr all_of
#' @importFrom tidyr any_of
#' @importFrom tidyr fill
## usethis namespace: end
NULL
